### ISSUE TITLE
in "htmf.min.v2.js" you have a wrong "," right before the second instance of "document."

### ISSUE THREAD

**Issue by learningnewthings** [jon49/MealPlanner#45]
(()=>{document.querySelectorAll("[hf-hidden]").forEach(t=>t instanceof HTMLElement&&(t.style.visibility="hidden")),document.addEventListener

before ",document.addEventListener" shouldn't be any comma, a space or a ";" would be the right thing

This breaks the whole code. 

UPDATE, this code is either too shit, or I've got no idea how this is able to work , there are other instances in the code where there are "," instead of ";" , and others things.

**Comment by jon49** [comment]
Yeah, I'm not sure why it has a comma instead of a semicolon there. The code does work though - so apparently it isn't "shit." I used a Go lang based tool called "minify" to minify that code. You can see the source code for my `HTMF` library here:

https://github.com/jon49/htmf/tree/master/src

A more full library that does much more than what I did is HTMX which [you can find here](https://htmx.org/).

The minify tool I used is here: https://github.com/tdewolff/minify
